version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: orders
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  mysql_test:
    image: mysql:5.7
    container_name: orders_test
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders-test
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306

