POST http://localhost:8000/orders HTTP/1.1
Content-Type: application/json

{
  "id": "23",
  "price": 10.0,
  "tax": 2.0
}

###
GET http://localhost:8000/orders HTTP/1.1
Content-Type: application/json